export const projects = [
  {
    title: 'Optical Manager PWA',
    description: "Aplicativo de gerenciamento para óticas. O controle que você precisa ter para o seu negócio.",
    image: '/images/Optical_Manager_img.png',
    tags: ['Mongo', 'Express', 'React', 'Node', 'Framer-motion'],
    source: 'https://github.com/FellipeLorram/Optical-manager.git',
    visit: 'https://optical-manager.vercel.app/',
    id: 0,
    right: true,
    color: '#6937FF',
  },  
  {
    title: 'MindCare',
    description: "Aplicativo de gerenciamento para profissionais na área da psicologia. Conexão total com o seu paciente.",
    image: '/images/Mind_Care_Img.png',
    tags: ['Mongo', 'Express', 'React', 'Node', 'Framer-motion'],
    source: 'https://github.com/FellipeLorram/MindCare.git',
    visit: 'https://elegant-liskov-7a1627.netlify.app/',
    id: 1,
    right: false,
    color: '#b86fdc',
  },
  {
    title: 'Gireh Managment',
    description: "Aplicativo de gerenciamento para rede de óticas Girêh.",
    image: '/images/Gireh_Managment.png',
    tags: ['Mongo', 'Express', 'Node', 'EJS'],
    source: 'https://github.com/FellipeLorram/Gireh-Gerenciamento.git',
    visit: '#',
    id: 2,
    right: true,
    color: '#404040',
  },
  /*
  
  {
    title: 'Site institucional Óticas Girêh',
    description: "Site institucional, parte do projeto acima.",
    image: '/images/Site-institucional-gireh.png',
    tags: ['Mongo', 'Express', 'Node', 'EJS'],
    source: 'https://github.com/FellipeLorram/SiteInstitucionalOticaGireh.git',
    visit: 'https://site-institucional-otica-gireh.vercel.app/',
    id: 1,
    right: false,
    color: '#404040',
  },
  {
    title: 'Site institucional Óticas Girêh',
    description: "Site institucional, parte do projeto acima.",
    image: '/images/Site-institucional-gireh.png',
    tags: ['Mongo', 'Express', 'Node', 'EJS'],
    source: 'https://github.com/FellipeLorram/Projeto-Maker.git',
    visit: 'https://projeto-maker-site.vercel.app/',
    id: 1,
    right: true,
    color: '#404040',
  },
    */
];
